import type { OxlintConfig } from "oxlint";

export const node: OxlintConfig = {
  overrides: [
    {
      files: ["**/*.{js,cjs,mjs,ts,mts,cts,jsx,tsx}"],
      plugins: ["node"],
      env: { es2024: true },
      rules: {
        "node/no-exports-assign": "error",
        "no-console": "off",
      },
      globals: {
        "__dirname": "off",
        "__filename": "off",
        "AbortController": "readonly",
        "AbortSignal": "readonly",
        "atob": "readonly",
        "Blob": "readonly",
        "BroadcastChannel": "readonly",
        "btoa": "readonly",
        "Buffer": "readonly",
        "ByteLengthQueuingStrategy": "readonly",
        "clearImmediate": "readonly",
        "clearInterval": "readonly",
        "clearTimeout": "readonly",
        "CloseEvent": "readonly",
        "CompressionStream": "readonly",
        "console": "readonly",
        "CountQueuingStrategy": "readonly",
        "crypto": "readonly",
        "Crypto": "readonly",
        "CryptoKey": "readonly",
        "CustomEvent": "readonly",
        "DecompressionStream": "readonly",
        "DOMException": "readonly",
        "Event": "readonly",
        "EventTarget": "readonly",
        "exports": "off",
        "fetch": "readonly",
        "File": "readonly",
        "FormData": "readonly",
        "global": "readonly",
        "Headers": "readonly",
        "MessageChannel": "readonly",
        "MessageEvent": "readonly",
        "MessagePort": "readonly",
        "module": "off",
        "navigator": "readonly",
        "Navigator": "readonly",
        "performance": "readonly",
        "Performance": "readonly",
        "PerformanceEntry": "readonly",
        "PerformanceMark": "readonly",
        "PerformanceMeasure": "readonly",
        "PerformanceObserver": "readonly",
        "PerformanceObserverEntryList": "readonly",
        "PerformanceResourceTiming": "readonly",
        "process": "readonly",
        "queueMicrotask": "readonly",
        "ReadableByteStreamController": "readonly",
        "ReadableStream": "readonly",
        "ReadableStreamBYOBReader": "readonly",
        "ReadableStreamBYOBRequest": "readonly",
        "ReadableStreamDefaultController": "readonly",
        "ReadableStreamDefaultReader": "readonly",
        "Request": "readonly",
        "require": "off",
        "Response": "readonly",
        "setImmediate": "readonly",
        "setInterval": "readonly",
        "setTimeout": "readonly",
        "structuredClone": "readonly",
        "SubtleCrypto": "readonly",
        "TextDecoder": "readonly",
        "TextDecoderStream": "readonly",
        "TextEncoder": "readonly",
        "TextEncoderStream": "readonly",
        "TransformStream": "readonly",
        "TransformStreamDefaultController": "readonly",
        "URL": "readonly",
        "URLSearchParams": "readonly",
        "WebAssembly": "readonly",
        "WebSocket": "readonly",
        "WritableStream": "readonly",
        "WritableStreamDefaultController": "readonly",
        "WritableStreamDefaultWriter": "readonly",
      },
    },
  ],
};
