import type { OxlintConfig } from "oxlint";

export const react: OxlintConfig = {
  overrides: [
    {
      files: ["**/*.{js,jsx,ts,tsx}"],
      plugins: ["react", "jsx-a11y"],
      rules: {
        "react/display-name": "error",
        "react/jsx-key": "error",
        "react/jsx-no-comment-textnodes": "error",
        "react/jsx-no-duplicate-props": "error",
        "react/jsx-no-target-blank": "error",
        "react/jsx-no-undef": "error",
        "react/no-children-prop": "error",
        "react/no-danger-with-children": "error",
        "react/no-direct-mutation-state": "error",
        "react/no-find-dom-node": "error",
        "react/no-is-mounted": "error",
        "react/no-render-return-value": "error",
        "react/no-string-refs": "error",
        "react/no-unescaped-entities": "error",
        "react/no-unknown-property": "error",
        "react/no-unsafe": "off",
        "react/react-in-jsx-scope": "off",
        "react/no-danger": "error",
        "react/no-did-mount-set-state": "error",
        "react/no-did-update-set-state": "error",
        "react/no-multi-comp": ["error", { ignoreStateless: true }],
        "react/no-redundant-should-component-update": "error",
        "react/no-this-in-sfc": "error",
        "react/no-will-update-set-state": "error",
        "react/prefer-es6-class": "error",
        "react/style-prop-object": "error",
        "react/void-dom-elements-no-children": "error",
        "react/jsx-filename-extension": "error",
        "react/self-closing-comp": "warn",
        "react/jsx-boolean-value": "warn",
        "react/jsx-curly-brace-presence": [
          "warn",
          { props: "never", children: "never" },
        ],
        "react/jsx-pascal-case": ["warn", { allowAllCaps: true }],
        "react/jsx-no-useless-fragment": "warn",
        "react/rules-of-hooks": "error",
        "react/exhaustive-deps": "warn",
        "jsx-a11y/alt-text": "error",
        "jsx-a11y/html-has-lang": "error",
        "jsx-a11y/aria-activedescendant-has-tabindex": "error",
        "jsx-a11y/aria-props": "error",
        "jsx-a11y/aria-proptypes": "error",
        "jsx-a11y/aria-role": "error",
        "jsx-a11y/aria-unsupported-elements": "error",
        "jsx-a11y/heading-has-content": "error",
        "jsx-a11y/iframe-has-title": "error",
        "jsx-a11y/interactive-supports-focus": "error",
        "jsx-a11y/label-has-associated-control": "error",
        "jsx-a11y/mouse-events-have-key-events": "error",
        "jsx-a11y/no-access-key": "error",
        "jsx-a11y/no-autofocus": "error",
        "jsx-a11y/no-distracting-elements": "error",
        "jsx-a11y/no-interactive-element-to-noninteractive-role": "error",
        "jsx-a11y/no-noninteractive-element-to-interactive-role": [
          "error",
          {
            ul: [
              "listbox",
              "menu",
              "menubar",
              "radiogroup",
              "tablist",
              "tree",
              "treegrid",
            ],
            ol: [
              "listbox",
              "menu",
              "menubar",
              "radiogroup",
              "tablist",
              "tree",
              "treegrid",
            ],
            li: ["option", "menuitem", "row", "tab", "treeitem"],
            table: ["grid"],
            td: ["gridcell"],
          },
        ],
        "jsx-a11y/no-noninteractive-element-interactions": [
          "error",
          {
            handlers: [
              "onClick",
              "onMouseDown",
              "onMouseUp",
              "onKeyPress",
              "onKeyDown",
              "onKeyUp",
            ],
          },
        ],
        "jsx-a11y/no-static-element-interactions": [
          "error",
          {
            handlers: [
              "onClick",
              "onMouseDown",
              "onMouseUp",
              "onKeyPress",
              "onKeyDown",
              "onKeyUp",
            ],
          },
        ],
        "jsx-a11y/anchor-has-content": "error",
        "jsx-a11y/anchor-is-valid": "error",
        "jsx-a11y/role-supports-aria-props": "error",
        "jsx-a11y/role-has-required-aria-props": "error",
        "jsx-a11y/autocomplete-valid": "error",
        "jsx-a11y/scope": "error",
        "jsx-a11y/tabindex-no-positive": "error",
        "jsx-a11y/img-redundant-alt": "error",
        "jsx-a11y/no-noninteractive-tabindex": [
          "error",
          { tags: [], roles: ["dialog", "tabpanel"] },
        ],
        // Disable rules from jsx-a11y recommended that don't fit our patterns
        "jsx-a11y/no-redundant-roles": "off",
        "jsx-a11y/click-events-have-key-events": "off",
      },
    },
  ],
};
